// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ73FA1P4kXDgnoi9Rj1BYfCaFonuelOg',
    appId: '1:335875494011:web:f830d67ab55341bbcf12de',
    messagingSenderId: '335875494011',
    projectId: 'plan-all-the-way',
    authDomain: 'plan-all-the-way.firebaseapp.com',
    storageBucket: 'plan-all-the-way.firebasestorage.app',
    measurementId: 'G-L8G8MYHXJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnTQ2yimGqCPPWRNmRKN5FIzij-i7EPi8',
    appId: '1:335875494011:android:eb0d29eac84e2ad7cf12de',
    messagingSenderId: '335875494011',
    projectId: 'plan-all-the-way',
    storageBucket: 'plan-all-the-way.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKpX7m9ewgWLPV8eRpI7Uvsqefme_ZwVw',
    appId: '1:335875494011:ios:bfefd44c78bb8b7ecf12de',
    messagingSenderId: '335875494011',
    projectId: 'plan-all-the-way',
    storageBucket: 'plan-all-the-way.firebasestorage.app',
    iosBundleId: 'com.example.planAllTheWay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKpX7m9ewgWLPV8eRpI7Uvsqefme_ZwVw',
    appId: '1:335875494011:ios:bfefd44c78bb8b7ecf12de',
    messagingSenderId: '335875494011',
    projectId: 'plan-all-the-way',
    storageBucket: 'plan-all-the-way.firebasestorage.app',
    iosBundleId: 'com.example.planAllTheWay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ73FA1P4kXDgnoi9Rj1BYfCaFonuelOg',
    appId: '1:335875494011:web:874aaa87c82bf0bccf12de',
    messagingSenderId: '335875494011',
    projectId: 'plan-all-the-way',
    authDomain: 'plan-all-the-way.firebaseapp.com',
    storageBucket: 'plan-all-the-way.firebasestorage.app',
    measurementId: 'G-TP7SM9CRY4',
  );
}
